# AMATH 422/522 Python Lab Manual, Part 2 

This tutorial draws heavily on sources including:

* The Allen Institute's superb Python Bootcamp, at https://github.com/AllenInstitute/SWDB_2019/tree/master/PythonBootcamp

I strongly encourage you to visit the Allen's Python Bootcamp for much more -- including a general introduction to Python's fundamental data structures and objects!  Here we will focus on getting going fast with numerical computing.

It is also draws on and translates much of the Lab Manual for our text -- Dynamic Models in Biology, by Ellner and Guckenheimer -- into Python.  That Lab Manual is available (in MATLAB and R) here.  Credits for this are:  *These notes for computer labs accompany our textbook {Dynamic Models in Biology} (Princeton University
Press 2006). They are based in part on course materials 
by former TAs Colleen Webb, Jonathan Rowell and Daniel Fink at Cornell, 
Professors Lou Gross (University of Tennessee) and Paul Fackler (NC State University), and 
on the book \textit{Getting Started with Matlab} by Rudra Pratap (Oxford University Press).* 



### Scipy

We'll import our usual plotting and numpy packages, and also one more new one, scipy.  Scipy has many subpackages with very useful functionality.  Highlights include:


<li>Integration and ODEs (scipy.integrate)
<li>Interpolation (scipy.interpolate)
<li>Input and output (scipy.io)
<li><b>Linear algebra</b> (scipy.linalg)
<li>Optimization and root finding (scipy.optimize)
<li><b>Signal processing</b> (scipy.signal)
<li>Sparse matrices (scipy.sparse)
<li><b>Statistical functions</b> (scipy.stats)


The common practice is to import these subpackages separately, with their own names.  We'll do that for the linalg and optimize functions here. 

In [2]:
import matplotlib.pylab as plt   # That gives plotting, and the next line makes plots appear inline in notebook
%matplotlib inline  
import numpy as np  # That gives numerical arrays and tools for manipulating them

import scipy.optimize as opt
import scipy.linalg as la

#### Root finding.
We'll use the brentq method scipy.optimize to find a function's roots:  that is, where it crosses zero.  This is an enhanced version of the most basic 'bisection' approach (adding interpolation), and likewise requires specifying an intial bracketing interval in which the root may lie.  

There are many other root finding methods in scipy:  see documentation for scipy.optimize (https://docs.scipy.org/doc/scipy/reference/optimize.html)

Let's test this out with a function with roots -1 and +1 

In [3]:
def f(x):
    return (x**2 - 1)

In [4]:
#search for root between left_bracket and right_bracket
left_bracket=-2
right_bracket=0

opt.brentq(f,left_bracket,right_bracket)

-1.0

### Basic linear algebra operations

We use `eig` to return eigenvalues and eigenvectors.  Let's start with a super simple matrix B_mat

In [5]:
B_mat=np.array([[1 ,1],[0 ,2 ]])
print(B_mat)

[[1 1]
 [0 2]]


`eig` will return a 1-D array (list) of eigenvalues and a 2-D array, with (by default), the usual (right) eigenvectors as columns:

In [11]:
l, v = la.eig(B_mat)
print('eigenvalue 1-D array=',l)
print('eigenvector 2_D array')
print(v)

#help(la.eig)   #uncomment for more :)

eigenvalue 1-D array= [1.+0.j 2.+0.j]
eigenvector 2_D array
[[1.         0.70710678]
 [0.         0.70710678]]


Note that python uses j for $\sqrt{-1}$

**Exercise:**  Check this by hand!

Let's define our Leslie Matrix from class, and repeat these operations.

In [16]:
A_mat=np.array([[0 ,1,5],[.5 ,0 ,0],[0 , .25 , 0]])
print(A_mat)

l, v = la.eig(A_mat)

np.set_printoptions(precision=3, suppress=True)
print('eigenvalue 1-D array=',l)
print('eigenvector 2_D array')
print(v)

[[0.   1.   5.  ]
 [0.5  0.   0.  ]
 [0.   0.25 0.  ]]
eigenvalue 1-D array= [ 1.047+0.j    -0.524+0.568j -0.524-0.568j]
eigenvector 2_D array
[[ 0.898+0.j     0.827+0.j     0.827-0.j   ]
 [ 0.429+0.j    -0.363-0.393j -0.363+0.393j]
 [ 0.102+0.j    -0.014+0.173j -0.014-0.173j]]


By default, these eigenvalues and eigenvectors are NOT sorted by the magnitude of eigenvalues.  Let's fix that, sorting from smallest (abs value) to largest!  See Tutorial 1 for a simple example and explanation of sorting.  

In [17]:
# sorted eigenvalues and eigenvectors
idx=np.argsort(np.abs(l))
l_sorted=l[idx]  
v_sorted=v[:,idx]   #rearrange eigenvectors in same order

print('eigenvalue 1-D array, sorted=',l_sorted)
print('eigenvector 2_D array, sorted')
print(v_sorted)

#return largest eigenvalue
lambda_max= l_sorted[-1]
print(lambda_max)

eigenvalue 1-D array, sorted= [-0.524+0.568j -0.524-0.568j  1.047+0.j   ]
eigenvector 2_D array, sorted
[[ 0.827+0.j     0.827-0.j     0.898+0.j   ]
 [-0.363-0.393j -0.363+0.393j  0.429+0.j   ]
 [-0.014+0.173j -0.014-0.173j  0.102+0.j   ]]
(1.0472757407711641+0j)


#### Solving Matrix-Vector equations Ax=b 

 This can be done with the solve function from `scipy.linalg'

In [18]:
A_mat = np.array([[1,1],[1,2]])
print(A_mat)
b_arr = np.array([1,1])
print(b_arr)

x = la.solve(A_mat, b_arr)
x

[[1 1]
 [1 2]]
[1 1]


array([1., 0.])

Check our answer:  (also do this in your head or on paper!)

In [19]:
np.dot(A_mat,x) - b_arr

array([0., 0.])